name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: 

jobs:
  build:
    name: Build & Export APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # این مرحله کاملاً ضدگلوله شد! اول پوشه‌ها را می‌سازد، بعد فایل pubspec را با زور بازنویسی می‌کند
      - name: Force Overwrite Pubspec & Install
        run: |
          flutter create --project-name tapsi_client .
          
          cat << 'EOF' > pubspec.yaml
          name: tapsi_client
          description: Tapsi Injector App
          publish_to: 'none'
          version: 1.0.0+1
          
          environment:
            sdk: '>=3.13.0 <4.0.0'
            
          dependencies:
            flutter:
              sdk: flutter
            http: ^1.2.0
            shared_preferences: ^2.2.2
            flutter_inappwebview: ^6.0.0
            
          flutter:
            uses-material-design: true
          EOF
          
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tapsi-Client-Release
          path: build/app/outputs/flutter-apk/app-release.apk
